site_name: Tea-Acompaño-Docs
pages:
    - Home: index.md
    - Aportes: aportes.md

theme: readthedocs

extra:
    social:
        - type: 'facebook'
          link: 'https://www.facebook.com/TeaAyudo'
